name: Unit tests
on:
  pull_request:
      branches: [ main, develop, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t test -f ./Dockerfile.test .
    - run: docker run test
