name: Docker Image CI
on:
    push:
        tags: '*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag prometheus-otiohome-exporter:latest
            - name: Tag the Docker image
              run: docker tag prometheus-otiohome-exporter:latest sguesdon/prometheus-otiohome-exporter:${{ env.RELEASE_VERSION }}
            - name: Login to repo
              run: docker login -u sguesdon -p ${{ secrets.DOCKER_IO_SECRET }} docker.io
            - name: Pushing image to repo
              run: docker push sguesdon/prometheus-otiohome-exporter:${{ env.RELEASE_VERSION }}
